#!/usr/bin/python3
import os
import requests
import argparse
import tempfile
import tarfile
import re
import io
import subprocess

BASE_URL = 'https://kelvin.cs.vsb.cz'
#BASE_URL = 'http://localhost:8000'

config_dir = os.environ.get('XDG_CONFIG_HOME', None) or os.path.join(os.environ['HOME'], '.config', 'kelvin')
with open(os.path.join(config_dir, 'token')) as f:
    token = f.read().strip()

def untar(session, url, dest='.'):
    res = session.get(url)
    with tarfile.open(fileobj=io.BytesIO(res.content)) as tar:
        tar.extractall(dest)

class Api:
    def __init__(self, base_url, token):
        self.base_url = base_url
        self.s = requests.Session()
        self.s.headers['Authorization'] = f'Bearer {token}'

        self.s.headers['Referer'] = base_url

    def url(self, path):
        if path.startswith("https://"):
            return path
        return "".join([self.base_url, path])

    def get(self, path):
        return self.s.get(self.url(path))

    def post(self, path, *kargs, **kwargs):
        return self.s.post(self.url(path), *kargs, **kwargs)

    def put(self, path, *kargs, **kwargs):
        return self.s.put(self.url(path), *kargs, **kwargs)


def get(api, args):
    m = re.search(f'task/\d+/(?P<student>[^/]+)', args.url)
    if not m:
        print("Invalid url")
        exit(1)
    parts = m.groupdict()

    download_url = f'{args.url.split("#")[0].rstrip("/")}/download'

    with tempfile.TemporaryDirectory() as temp_dir:
        os.chdir(temp_dir)

        res = api.get(args.url)
        m = re.search(r'href="([^"]+)"[^>]+>Download all tests', res.content.decode('utf-8'))
        if m:
            print("Downloading tests")
            os.mkdir("tests")
            untar(api, f"/{m.group(1)}", "tests")

        untar(api, download_url)

        bash_history_path = os.path.join(config_dir, "bash_history")
        if not os.path.exists(bash_history_path):
            with open(bash_history_path, 'a'): pass

        subprocess.Popen([
            "docker", "run", "-w", "/work",
            "-v", "/tmp:/tmp",
            "-v", f"{temp_dir}:/work",
            "-v", f"{bash_history_path}:/root/.bash_history",
            "-e", "DISPLAY=:0",
            "-it", "kelvin/gcc",
            "sh", "-c", "/entry.py; cat result.html; rm result.html; echo; exec bash"
        ]).wait()
        """
        subprocess.check_call(["chmod", "-R", "a+rwX", temp_dir])
        subprocess.check_call(["xhost", "+localhost"])
        subprocess.Popen([
            "sudo",
            "systemd-run",
            "--working-directory", "/submit",
            "-E", f"PS1={parts['student']}$ ",
            "-E", "DISPLAY=:0",
            "-E", "HOME=/tmp",
            #"-p", "PrivateDevices=yes",
            "-p", "PrivateNetwork=yes",
            "-p", "DynamicUser=yes",
            "-p", f"BindPaths={temp_dir}:/submit:norbind",
            "-p", f"BindPaths=/tmp/.X11-unix:/tmp/.X11-unix:norbind",
            "-p", "ProtectSystem=strict",
            "-p", "ProtectHome=true",
            "-t",
#            "/bin/bash", "-i", "-c", f"if [ -f Makefile ]; then make clean; make; else gcc *.c -o main -fsanitize=address -g; fi; PS1='{parts['student']} \W $ ' exec bash --norc"
            "/bin/bash", "-i", "-c", f"if [ -f Makefilef ]; then make clean; make; else g++ *.cpp -lpthread -o main -fsanitize=address -g; fi; PS1='{parts['student']} \W $ ' exec bash --norc"
        ]).wait()
        """

def script(api, args):
    with open(args.path) as f:
        exec(f.read())

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='cmd', required=True)

    p = subparsers.add_parser('get')
    p.add_argument('url')

    p = subparsers.add_parser('script')
    p.add_argument('path')
    p.add_argument('remaining', nargs=argparse.REMAINDER)

    args = parser.parse_args()

    api = Api(BASE_URL, token)
    (locals()[args.cmd])(api, args)
